### ISSUE TITLE
单例模式--实现方式二：为何“不能完全避免并发带来的破坏”

### ISSUE THREAD

**Issue by Piasy** [simple-android-framework/android_design_patterns_analysis#2]
请问double-check方式哪里会有并发带来的破坏呢？
创建的话是可以避免多次创建的：如果已经创建过，任何读得线程都可以直接返回；如果未创建，则第一个进入if分支的线程持有锁，其他线程都要等待，因为有double-check，所以其他线程也不会再次创建；
这样子读取过程也没问题吧？

**Comment by hehonghui** [comment]
你可以查一下DCL失效问题

在 2015年3月23日 下午9:03，Xu Jianlin notifications@github.com写道：

**Comment by Piasy** [comment]
受教！
